title: Sidney's Blog
description: Research notes & other miscelleanous thoughts
timezone: UTC

baseurl: https://selene-huang.github.io/sidney-blog/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
