# title: "Sidney's Blog"
# description: "Research notes & other miscelleanous thoughts"
# timezone: UTC

baseurl: "/sidney-blog"
url: "https://selene-huang.github.io"

collections:
  index:
    output: true
